services:
  frontend:
    build:
      context: .
      dockerfile: apps/ai-budget/Dockerfile
    container_name: ai-budget
    ports:
      - '4200:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
