version: "3.8"

services:
  # Development service for Angular
  frontend-dev:
    image: node:20-alpine
    container_name: cockpit-app-dev
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "4200:4200"
    command: >
      sh -c "npm install && 
             npm start -- --host 0.0.0.0 --port 4200"
    environment:
      - NODE_ENV=development

  # Production build service
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cockpit-app-prod
    ports:
      - "4200:80"
    # Comment out the line below during development
    # profiles: ["production"]

  # Backend API service (uncomment and configure if needed)
  # backend:
  #   image: your-backend-image
  #   container_name: backend-api
  #   ports:
  #     - "8000:8000"
