services:
  frontend:
    build:
      context: .
      dockerfile: apps/cockpit-app/Dockerfile
    container_name: cockpit-app
    ports:
      - '4200:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
