services:
  ai-budget:
    image: ${AI_BUDGET_IMAGE:-ghcr.io/marcinparda/cockpit-app/ai-budget:latest}
    container_name: ai-budget
    ports:
      - '4200:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  todo:
    image: ${TODO_IMAGE:-ghcr.io/marcinparda/cockpit-app/todo:latest}
    container_name: todo
    ports:
      - '4201:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
