services:
  frontend-dev:
    image: node:20-alpine
    container_name: cockpit-app-dev
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "4200:4200"
    command: >
      sh -c "
             if [ ! -f src/environments/environment.ts ]; then
               cp src/environments/environment.template.ts src/environments/environment.ts;
             fi &&
             if [ ! -f src/environments/environment.development.ts ]; then
               cp src/environments/environment.development.template.ts src/environments/environment.development.ts;
             fi &&
             npm install && 
             npm start -- --host 0.0.0.0 --port 4200"
    environment:
      - NODE_ENV=development
