services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cockpit-app
    ports:
      - '4200:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
