services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cockpit-app
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - API_URL=${API_URL:-http://localhost:8000}
