services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cockpit-app
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
      - API_URL=http://api.production.com
