services:
  ai-budget:
    build:
      context: .
      dockerfile: apps/ai-budget/Dockerfile
    container_name: ai-budget
    ports:
      - '4200:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  shopping:
    build:
      context: .
      dockerfile: apps/shopping/Dockerfile
    container_name: shopping
    ports:
      - '4201:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
