name: Build Images

on:
  workflow_call:
    secrets:
      API_URL:
        required: true
    outputs:
      image_name:
        description: 'The built Docker image name'
        value: ${{ jobs.build-images.outputs.image_name }}
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build.outputs.digest }}
      image_name: ghcr.io/${{ github.repository }}/cockpit-frontend-apps:${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/cockpit-frontend-apps:latest
            ghcr.io/${{ github.repository }}/cockpit-frontend-apps:${{ github.sha }}
          platforms: linux/arm64 # linux/arm64 for ARM devices like Raspberry Pi
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            API_URL=${{ secrets.API_URL }}

      - name: Build Summary
        run: |
          echo "## 🐳 Docker Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Build Status**: Successful" >> $GITHUB_STEP_SUMMARY
          echo "📦 **Repository**: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "🏷️ **Tags pushed**:" >> $GITHUB_STEP_SUMMARY
          echo "- \`ghcr.io/${{ github.repository }}/cockpit-frontend-apps:latest\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`ghcr.io/${{ github.repository }}/cockpit-frontend-apps:${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🔗 **Registry URL**: https://github.com/${{ github.repository }}/pkgs/container/cockpit-frontend-apps" >> $GITHUB_STEP_SUMMARY
          echo "📝 **Commit**: [\`${{ github.sha }}\`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})" >> $GITHUB_STEP_SUMMARY
          echo "👤 **Triggered by**: @${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
