name: Pull down and compose up
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: connect to remote server
        uses: Gustavo-caetano/cloudflared-ssh-action@1.1
        with:
          host: ${{ secrets.CLOUDFLARE_TUNNEL_DOMAIN }}
          username: ${{ secrets.RASPBERRY_PI_USERNAME }}
          private_key: ${{ secrets.RASPBERRY_PI_SSH_KEY }}
          port: 22
          commands: cd ~ && mkdir hello-world
