name: Deploy to Production

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      deployment-type:
        description: 'Deployment type'
        required: false
        default: 'affected'
        type: choice
        options:
          - affected
          - full

jobs:
  deploy:
    name: Deploy Applications
    uses: ./.github/workflows/deploy-nx-affected.yml
    with:
      force-full-deployment: ${{ inputs.deployment-type == 'full' }}
    secrets:
      RASPBERRY_PI_SSH_KEY: ${{ secrets.RASPBERRY_PI_SSH_KEY }}
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      CLOUDFLARE_TUNNEL_DOMAIN: ${{ secrets.CLOUDFLARE_TUNNEL_DOMAIN }}
      RASPBERRY_PI_USERNAME: ${{ secrets.RASPBERRY_PI_USERNAME }}
      API_URL: ${{ secrets.API_URL }}
