name: Deploy to Production

on:
  push:
    branches: [master]

jobs:
  validate-types:
    name: Validate API Types
    uses: ./.github/workflows/validate-types.yml
    with:
      create-pr-on-drift: false
      force-update-types: false

  build-and-test-todo:
    name: Build and Test Applications
    uses: ./.github/workflows/build-and-test.yml
    with:
      app-name: 'todo'
      configuration: 'production'
      run-tests: false
    secrets:
      API_URL: ${{ secrets.API_URL }}

  build-and-test-ai-budget:
    name: Build and Test Applications
    uses: ./.github/workflows/build-and-test.yml
    with:
      app-name: 'ai-budget'
      configuration: 'production'
      run-tests: false
    secrets:
      API_URL: ${{ secrets.API_URL }}

  deploy:
    name: Deploy to Production
    needs: [validate-types, build-and-test-todo, build-and-test-ai-budget]
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: 'production'
      skip-pre-check: false
    secrets:
      RASPBERRY_PI_SSH_KEY: ${{ secrets.RASPBERRY_PI_SSH_KEY }}
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      CLOUDFLARE_TUNNEL_DOMAIN: ${{ secrets.CLOUDFLARE_TUNNEL_DOMAIN }}
      RASPBERRY_PI_USERNAME: ${{ secrets.RASPBERRY_PI_USERNAME }}
      API_URL: ${{ secrets.API_URL }}
