name: Deploy

on:
  push:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  validate-types:
    name: Validate API Types
    uses: ./.github/workflows/validate-types.yml
    with:
      create-pr-on-drift: false
      force-update-types: false

  build-images:
    needs: [checks, validate-types]
    uses: ./.github/workflows/build-images.yml

  deploy-to-raspberry:
    needs: build-images
    uses: ./.github/workflows/deploy-to-production.yml
    with:
      image-name: '${{ needs.build-images.outputs.image_name }}'
    secrets:
      CLOUDFLARE_TUNNEL_DOMAIN: ${{ secrets.CLOUDFLARE_TUNNEL_DOMAIN }}
      RASPBERRY_PI_USERNAME: ${{ secrets.RASPBERRY_PI_USERNAME }}
      RASPBERRY_PI_SSH_KEY: ${{ secrets.RASPBERRY_PI_SSH_KEY }}
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
