name: Scheduled Type Drift Check

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      force-update:
        description: 'Force update types even if no drift'
        required: false
        default: false
        type: boolean

jobs:
  scheduled-type-check:
    name: Scheduled Type Drift Check
    uses: ./.github/workflows/validate-types.yml
    with:
      create-pr-on-drift: true
      force-update-types: ${{ github.event_name == 'workflow_dispatch' && inputs.force-update || false }}

  notify-on-drift:
    name: Notify on Type Drift
    needs: [scheduled-type-check]
    runs-on: ubuntu-latest
    if: needs.scheduled-type-check.outputs.drift-detected == 'true'

    steps:
      - name: Create Issue for Type Drift
        uses: actions/github-script@v6
        with:
          script: |
            const issueTitle = '🚨 API Type Drift Detected - Action Required';
            const issueBody = `
            ## 🔄 API Type Drift Detection Alert

            Our scheduled type validation has detected changes in the OpenAPI specification.

            ### Detection Details
            - **Detection Time**: ${new Date().toISOString()}
            - **Trigger**: Scheduled daily check
            - **Drift Status**: Changes detected in API specification
            - **Validation Status**: ${{ needs.scheduled-type-check.outputs.validation-status }}

            ### Automatic Actions Taken
            - ✅ Fresh types generated from latest API specification
            - ✅ All 11 type libraries updated
            - ✅ Type coverage and compilation verified
            - ✅ Pull request created with updated types

            ### Next Steps Required
            1. **Review the automatically created PR** for type changes
            2. **Test the updated types** in a development environment
            3. **Merge the PR** when ready to deploy updated types
            4. **Deploy to production** to use the latest types

            ### Impact Assessment
            - Applications using the affected types may need updates
            - Review any breaking changes in the API specification
            - Consider updating dependent code if necessary

            ### Monitoring
            This issue will be automatically closed when the associated PR is merged.

            ---
            **Auto-generated by scheduled workflow** • [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;

            // Check if similar issue already exists
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['api-drift', 'automated']
            });

            const existingIssue = issues.find(issue => 
              issue.title.includes('API Type Drift Detected')
            );

            if (existingIssue) {
              // Update existing issue
              await github.rest.issues.createComment({
                issue_number: existingIssue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 🔄 Additional Drift Detected\n\n**Time**: ${new Date().toISOString()}\n**Status**: New changes detected in API specification\n\nPlease review the latest automated PR for additional type updates.`
              });
            } else {
              // Create new issue
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issueTitle,
                body: issueBody,
                labels: ['api-drift', 'automated', 'high-priority']
              });
            }

  cleanup-old-branches:
    name: Cleanup Old Type Update Branches
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up old automated branches
        uses: actions/github-script@v6
        with:
          script: |
            const { data: branches } = await github.rest.repos.listBranches({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            // Find branches that match our automated pattern and are older than 7 days
            const automatedBranches = branches.filter(branch => 
              branch.name.startsWith('automated/api-types-update-')
            );

            for (const branch of automatedBranches) {
              try {
                // Get branch details to check age
                const { data: branchData } = await github.rest.repos.getBranch({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  branch: branch.name
                });
                
                const branchDate = new Date(branchData.commit.commit.committer.date);
                const daysSinceBranch = (Date.now() - branchDate.getTime()) / (1000 * 60 * 60 * 24);
                
                // Delete branches older than 7 days
                if (daysSinceBranch > 7) {
                  await github.rest.git.deleteRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: `heads/${branch.name}`
                  });
                  
                  console.log(`Deleted old automated branch: ${branch.name}`);
                }
              } catch (error) {
                console.log(`Could not process branch ${branch.name}: ${error.message}`);
              }
            }
