name: Scheduled Type Drift Check

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      force-update:
        description: 'Force update types even if no drift'
        required: false
        default: false
        type: boolean

jobs:
  scheduled-type-check:
    name: Scheduled Type Drift Check
    uses: ./.github/workflows/validate-types.yml


  create-pr-on-drift:
    name: Create PR on Type Drift
    needs: [scheduled-type-check]
    runs-on: ubuntu-latest
    if: needs.scheduled-type-check.outputs.has_drift == 'true' || github.event.inputs.force-update == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create unique branch name
        id: branch-info
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          BRANCH_NAME="chore/update-api-types-${TIMESTAMP}"
          echo "branch-name=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          echo "timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT

      - name: Create and switch to new branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b ${{ steps.branch-info.outputs.branch-name }}

      - name: Update API types
        run: |
          echo "🔄 Fetching latest API types..."
          npm run update:types

      - name: Verify type compilation after update
        run: |
          echo "🔨 Verifying updated types compile correctly..."
          npx nx run-many --target=lint,build --projects=api-types

      - name: Check for changes
        id: git-check
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "has-changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "has-changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.git-check.outputs.has-changes == 'true'
        run: |
          git commit -m "chore: update API types from remote OpenAPI specification

          🔄 Automated update of API types
          📅 Updated on: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
          🤖 Generated by: Scheduled Type Drift Check workflow

          This PR was automatically created because type drift was detected
          between the local OpenAPI specification and the remote version at
          https://api.parda.me/openapi.json"

      - name: Push branch
        if: steps.git-check.outputs.has-changes == 'true'
        run: |
          git push origin ${{ steps.branch-info.outputs.branch-name }}

      - name: Create Pull Request
        if: steps.git-check.outputs.has-changes == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔄 Auto-update API types - ${{ steps.branch-info.outputs.timestamp }}',
              head: '${{ steps.branch-info.outputs.branch-name }}',
              base: 'master',
              body: `## 🤖 Automated API Types Update

            This PR was automatically created because **type drift** was detected during the scheduled check.

            ### 📋 Summary
            - **Source**: Remote OpenAPI specification at \`https://api.parda.me/openapi.json\`
            - **Updated**: \`$(date -u '+%Y-%m-%d %H:%M:%S UTC')\`
            - **Trigger**: ${{ github.event_name == 'schedule' && 'Scheduled daily check' || 'Manual workflow dispatch' }}

            ### 🔍 What Changed
            The remote OpenAPI specification has been updated, and this PR brings our local types in sync with those changes.

            ### ✅ Verification
            - [x] Types fetched from remote OpenAPI spec
            - [x] TypeScript compilation successful
            - [x] All type libraries lint and build correctly

            ### 🚀 Next Steps
            1. Review the changes in this PR
            2. Test any affected applications
            3. Merge when ready

            ---
            *This PR was created automatically by the Scheduled Type Drift Check workflow.*
            `
            });

            console.log(\`Pull request created: #\${pr.number}\`);

      - name: Summary
        run: |
          if [ "${{ steps.git-check.outputs.has-changes }}" == "true" ]; then
            echo "✅ Successfully created PR for type updates"
            echo "🔗 Branch: ${{ steps.branch-info.outputs.branch-name }}"
          else
            echo "ℹ️  No changes were needed after running update:types"
            echo "🤔 This might indicate a validation issue or the types were already current"
          fi
